spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product-db
    username: postgres
    password: walnut@2
  jpa:
    show-sql: true
  application:
    name: product-api
server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

